### ISSUE TITLE
Change Quiz Scoring System

### ISSUE THREAD

**Issue by emctague** [emctague/editor#2]
**Current Scoring:**
Editors can be 'benefited' by question answers, increasing their score by 1. Editors can be rendered ineligible by question answers, entirely removing them as possibilities.

**Proposed Scoring:**
Editors could have their score changed relative to the current score by specific amounts. Instead of ineligibility, the scores of certain editors would simply be decreased slightly.

**Comment by jacwib** [comment]
Pr #4 fixes this
